// Copyright 2026 Daniel Valdivia
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.34.1
// source: internal/otel/notify/notify.proto

package notify

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_internal_otel_notify_notify_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_otel_notify_notify_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_internal_otel_notify_notify_proto_rawDescGZIP(), []int{0}
}

// ErrorEvent is a minimal projection of an OTLP log record. Sent for every
// record whose severity meets or exceeds the collector's MinSeverity.
type ErrorEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unix nanoseconds (lr.time_unix_nano, falling back to observed time).
	TimestampUnixNano int64 `protobuf:"varint,1,opt,name=timestamp_unix_nano,json=timestampUnixNano,proto3" json:"timestamp_unix_nano,omitempty"`
	// service.name resource attribute, or "unknown".
	ServiceName string `protobuf:"bytes,2,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	// Human-readable severity label (e.g. "ERROR", "FATAL").
	Severity string `protobuf:"bytes,3,opt,name=severity,proto3" json:"severity,omitempty"`
	// Log record body as a string.
	Body          string `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorEvent) Reset() {
	*x = ErrorEvent{}
	mi := &file_internal_otel_notify_notify_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorEvent) ProtoMessage() {}

func (x *ErrorEvent) ProtoReflect() protoreflect.Message {
	mi := &file_internal_otel_notify_notify_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorEvent.ProtoReflect.Descriptor instead.
func (*ErrorEvent) Descriptor() ([]byte, []int) {
	return file_internal_otel_notify_notify_proto_rawDescGZIP(), []int{1}
}

func (x *ErrorEvent) GetTimestampUnixNano() int64 {
	if x != nil {
		return x.TimestampUnixNano
	}
	return 0
}

func (x *ErrorEvent) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *ErrorEvent) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *ErrorEvent) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

var File_internal_otel_notify_notify_proto protoreflect.FileDescriptor

const file_internal_otel_notify_notify_proto_rawDesc = "" +
	"\n" +
	"!internal/otel/notify/notify.proto\x12\x17tukituki.otel.notify.v1\"\x12\n" +
	"\x10SubscribeRequest\"\x8f\x01\n" +
	"\n" +
	"ErrorEvent\x12.\n" +
	"\x13timestamp_unix_nano\x18\x01 \x01(\x03R\x11timestampUnixNano\x12!\n" +
	"\fservice_name\x18\x02 \x01(\tR\vserviceName\x12\x1a\n" +
	"\bseverity\x18\x03 \x01(\tR\bseverity\x12\x12\n" +
	"\x04body\x18\x04 \x01(\tR\x04body2i\n" +
	"\bNotifier\x12]\n" +
	"\tSubscribe\x12).tukituki.otel.notify.v1.SubscribeRequest\x1a#.tukituki.otel.notify.v1.ErrorEvent0\x01B;Z9github.com/dvaldivia/tukituki/internal/otel/notify;notifyb\x06proto3"

var (
	file_internal_otel_notify_notify_proto_rawDescOnce sync.Once
	file_internal_otel_notify_notify_proto_rawDescData []byte
)

func file_internal_otel_notify_notify_proto_rawDescGZIP() []byte {
	file_internal_otel_notify_notify_proto_rawDescOnce.Do(func() {
		file_internal_otel_notify_notify_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_otel_notify_notify_proto_rawDesc), len(file_internal_otel_notify_notify_proto_rawDesc)))
	})
	return file_internal_otel_notify_notify_proto_rawDescData
}

var file_internal_otel_notify_notify_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_otel_notify_notify_proto_goTypes = []any{
	(*SubscribeRequest)(nil), // 0: tukituki.otel.notify.v1.SubscribeRequest
	(*ErrorEvent)(nil),       // 1: tukituki.otel.notify.v1.ErrorEvent
}
var file_internal_otel_notify_notify_proto_depIdxs = []int32{
	0, // 0: tukituki.otel.notify.v1.Notifier.Subscribe:input_type -> tukituki.otel.notify.v1.SubscribeRequest
	1, // 1: tukituki.otel.notify.v1.Notifier.Subscribe:output_type -> tukituki.otel.notify.v1.ErrorEvent
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_otel_notify_notify_proto_init() }
func file_internal_otel_notify_notify_proto_init() {
	if File_internal_otel_notify_notify_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_otel_notify_notify_proto_rawDesc), len(file_internal_otel_notify_notify_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_otel_notify_notify_proto_goTypes,
		DependencyIndexes: file_internal_otel_notify_notify_proto_depIdxs,
		MessageInfos:      file_internal_otel_notify_notify_proto_msgTypes,
	}.Build()
	File_internal_otel_notify_notify_proto = out.File
	file_internal_otel_notify_notify_proto_goTypes = nil
	file_internal_otel_notify_notify_proto_depIdxs = nil
}
